// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFavorite(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddImageTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAllTags(arg1:string):Promise<Record<string, Array<string>>>;

export function GetFavorites():Promise<Array<main.Favorite>>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetImageTags(arg1:string,arg2:string):Promise<Array<string>>;

export function GetSettings():Promise<main.Settings>;

export function Greet(arg1:string):Promise<string>;

export function IsFavorite(arg1:string):Promise<boolean>;

export function ListDir(arg1:string):Promise<Array<main.FileEntry>>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function RemoveFavorite(arg1:string):Promise<void>;

export function RemoveImageTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetImageTags(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function UpdateSettings(arg1:number,arg2:number):Promise<void>;
