// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetImageBase64(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListDir(arg1:string):Promise<Array<main.FileEntry>>;
