// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFavorite'](arg1, arg2, arg3);
}

export function AddImageTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddImageTag'](arg1, arg2, arg3);
}

export function GetAllTags(arg1) {
  return window['go']['main']['App']['GetAllTags'](arg1);
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetImageTags(arg1, arg2) {
  return window['go']['main']['App']['GetImageTags'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUIState() {
  return window['go']['main']['App']['GetUIState']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function RemoveFavorite(arg1) {
  return window['go']['main']['App']['RemoveFavorite'](arg1);
}

export function RemoveImageTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveImageTag'](arg1, arg2, arg3);
}

export function SaveUIState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveUIState'](arg1, arg2, arg3, arg4, arg5);
}

export function SetImageTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetImageTags'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2);
}
